language: scala
scala:
  - 2.11.12
  - 2.12.12
jdk:
  - openjdk8
notifications:
  slack: thenewmotion:AXSluctig1mmZbeKRDeeY41s
script: sbt ++$TRAVIS_SCALA_VERSION test
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
