language: scala
scala:
  - 2.11.8
  - 2.12.1
jdk:
  - oraclejdk8
notifications:
  slack: thenewmotion:AXSluctig1mmZbeKRDeeY41s
script: sbt ++$TRAVIS_SCALA_VERSION test
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
